experiment_name: "SNN_ResNet18_RateEncoding"
description: "Spiking ResNet-18 U-Net with standard LIF neurons and Rate encoding. (SANITY CHECK)"

data:
  dataset_path: "data/eeg_emotions_processed"
  encoding_method: "latency"
  num_timesteps: 32
  window_size:  256
  sampling_rate: 256
  step_size: 128
  grid_size:  64
  freq_bands: 5
  num_channels: 14
  train_split: 0.8
  num_workers: 4
  num_samples: 2000
  

mask:
  type: "data_driven"
  sigma: 5.0

model:
  type: "SpikingUNet"
  encoder_type: "ResNet18"
  in_channels: 5
  num_classes: 5
  dropout: 0.2

neuron_params:
  spike_model: "snn.Leaky" 
  beta: 0.9
  alpha: 0.5
  threshold: 0.1
  learn_threshold: true
  learn_alpha: true
  learn_beta: false
  spike_grad_alpha: 0.5

training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.0

loss:
  smooth: 0.
  lambda_seg: 1.0
  lambda_bce: 1.5
  lambda_class: 0.5
  alpha: 0.8
  beta: 0.2

logging:
  project_name: "snn-encoding-showdown"  # The name of the project on the website
  run_name: "Sanity_ResNet18_Latency"    # A specific name for this experiment
  tags: ["sanity-check", "resnet18", "latency", "snn"] # Tags for filtering later
  offline: false  # Set to true if you have no internet and want to sync later
  log_interval: 1